/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tetris;

/**
 *
 * @author ferol
 */
public class MainMenu extends javax.swing.JFrame {

    Tablero tablero;
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        butLoadGame = new java.awt.Button();
        butNewGame = new java.awt.Button();
        buttExitGame = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tetris!");
        setBackground(new java.awt.Color(209, 85, 84));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        label1.setFont(new java.awt.Font("Linux Biolinum Keyboard O", 0, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(28, 135, 159));
        label1.setText("Tetris");

        butLoadGame.setLabel("Load Game");
        butLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoadGameActionPerformed(evt);
            }
        });

        butNewGame.setLabel("New Game");
        butNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNewGameActionPerformed(evt);
            }
        });

        buttExitGame.setLabel("Exit Game");
        buttExitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttExitGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttExitGame, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(butNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(butNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttExitGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        butLoadGame.getAccessibleContext().setAccessibleName("buttLoadGame");
        butNewGame.getAccessibleContext().setAccessibleName("butNewGame");
        buttExitGame.getAccessibleContext().setAccessibleName("buttExitGame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNewGameActionPerformed
        Tablero tablero = new Tablero();
        tablero.setVisible(true);
        tablero.threadFigura.start();
        this.setVisible(false);
    }//GEN-LAST:event_butNewGameActionPerformed

    private void butLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoadGameActionPerformed
        Tablero tablero = new Tablero();
        new formLoad(tablero).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_butLoadGameActionPerformed

    private void buttExitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttExitGameActionPerformed
        dispose();
    }//GEN-LAST:event_buttExitGameActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button butLoadGame;
    private java.awt.Button butNewGame;
    private java.awt.Button buttExitGame;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
